### ISSUE TITLE
Fetcher 下载的文件编码错误

### ISSUE THREAD

**Issue by Liu233w** [gavincook/githubOfflineInstaller#2]
下载得到的 `GitHub.application` 在我的机器上的编码是 UTF-8（含bom）。导致后续的步骤无法继续解析。手动把编码改成不含bom的utf-8之后才能解析成功。

环境：
windows10 x64
java 1.8.0
maven 3.3.9

我是从命令行用maven build出来的jar文件。

**Comment by gavincook** [comment]
测试时，带bom的也可以进行安装。现在已经统一移除了bom。
